import type { Event, Flyer, Instructor } from './schema'

export const MOCK_FLYERS: Flyer[] = [
  {
    id: 'flyer-001',
    title: 'Nashville Zouk Social — June 2026',
    imageUrl: '/mock/flyer-1.svg',
    imageKey: 'mock/flyer-1.svg',
    eventId: 'evt-001',
    isCurrent: true,
    createdAt: new Date('2026-05-15'),
    updatedAt: new Date('2026-05-15'),
  },
  {
    id: 'flyer-002',
    title: 'Beginner Zouk Intensive — June 2026',
    imageUrl: '/mock/flyer-2.svg',
    imageKey: 'mock/flyer-2.svg',
    eventId: 'evt-002',
    isCurrent: false,
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: 'flyer-003',
    title: 'Nashville Zouk Social — July 2026',
    imageUrl: '/mock/flyer-3.svg',
    imageKey: 'mock/flyer-3.svg',
    eventId: 'evt-004',
    isCurrent: false,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
  {
    id: 'flyer-004',
    title: 'Nashville Zouk Social — May 2026',
    imageUrl: '/mock/flyer-4.svg',
    imageKey: 'mock/flyer-4.svg',
    eventId: null,
    isCurrent: false,
    createdAt: new Date('2026-04-20'),
    updatedAt: new Date('2026-04-20'),
  },
]

export const MOCK_FLYER = MOCK_FLYERS[0]

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-001',
    title: 'Nashville Zouk Social',
    slug: 'nashville-zouk-social-june-2026',
    description:
      'Join us for our monthly social dance night! All levels welcome. Open floor with Brazilian Zouk music all night. Come early for a free beginner lesson at 8pm.',
    startDatetime: new Date('2026-06-06T21:00:00-05:00'),
    endDatetime: new Date('2026-06-07T01:00:00-05:00'),
    locationName: 'The Standard',
    locationAddress: '2124 8th Ave S, Nashville, TN 37204',
    locationUrl: 'https://maps.google.com/?q=2124+8th+Ave+S+Nashville+TN',
    eventType: 'social',
    isPublished: true,
    flyerId: 'flyer-001',
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date('2026-05-01'),
  },
  {
    id: 'evt-002',
    title: 'Beginner Zouk Intensive',
    slug: 'beginner-zouk-intensive-june-2026',
    description:
      'A 3-hour intensive workshop for beginners covering the fundamentals of Brazilian Zouk. No partner or prior dance experience needed. Registration required.',
    startDatetime: new Date('2026-06-14T14:00:00-05:00'),
    endDatetime: new Date('2026-06-14T17:00:00-05:00'),
    locationName: 'Nashville Dance Studio',
    locationAddress: '1900 Belmont Blvd, Nashville, TN 37212',
    locationUrl: 'https://maps.google.com/?q=1900+Belmont+Blvd+Nashville+TN',
    eventType: 'workshop',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: 'evt-003',
    title: 'Zouk Fundamentals — Weekly Class',
    slug: 'zouk-fundamentals-class-june-19',
    description:
      'Ongoing weekly class series. This week: connection and lead/follow principles. Drop-ins welcome.',
    startDatetime: new Date('2026-06-19T19:00:00-05:00'),
    endDatetime: new Date('2026-06-19T20:30:00-05:00'),
    locationName: 'Centennial Arts Center',
    locationAddress: '330 31st Ave N, Nashville, TN 37203',
    locationUrl: 'https://maps.google.com/?q=330+31st+Ave+N+Nashville+TN',
    eventType: 'class',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: 'evt-004',
    title: 'Nashville Zouk Social',
    slug: 'nashville-zouk-social-july-2026',
    description:
      'Our monthly social dance night. All levels welcome. Come dance Brazilian Zouk with Nashville\'s Zouk community.',
    startDatetime: new Date('2026-07-11T21:00:00-05:00'),
    endDatetime: new Date('2026-07-12T01:00:00-05:00'),
    locationName: 'The Standard',
    locationAddress: '2124 8th Ave S, Nashville, TN 37204',
    locationUrl: 'https://maps.google.com/?q=2124+8th+Ave+S+Nashville+TN',
    eventType: 'social',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
]

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: 'inst-001',
    name: 'Justin',
    slug: 'justin',
    bio: '',
    photoUrl: '/mock/instructor-justin.svg',
    photoKey: 'mock/instructor-justin.svg',
    instagramHandle: null,
    responsibilities: 'Instructor, Organizer',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'inst-002',
    name: 'Shelby',
    slug: 'shelby',
    bio: '',
    photoUrl: '/mock/instructor-shelby.svg',
    photoKey: 'mock/instructor-shelby.svg',
    instagramHandle: null,
    responsibilities: 'Instructor',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
]
