import type { Event, Flyer, Instructor } from './schema'

export const MOCK_FLYER: Flyer = {
  id: 'flyer-001',
  title: 'Nashville Zouk Social — June 2026',
  imageUrl: 'https://placehold.co/600x800/111827/f9a8d4?text=Nashville+Zouk+Social%0AJune+7%2C+2026',
  imageKey: 'mock/flyer-001.jpg',
  eventId: 'evt-001',
  isCurrent: true,
  createdAt: new Date('2026-05-15'),
  updatedAt: new Date('2026-05-15'),
}

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-001',
    title: 'Nashville Zouk Social',
    slug: 'nashville-zouk-social-june-2026',
    description:
      'Join us for our monthly social dance night! All levels welcome. Open floor with Brazilian Zouk music all night. Come early for a free beginner lesson at 8pm.',
    startDatetime: new Date('2026-06-06T21:00:00-05:00'),
    endDatetime: new Date('2026-06-07T01:00:00-05:00'),
    locationName: 'The Standard',
    locationAddress: '2124 8th Ave S, Nashville, TN 37204',
    locationUrl: 'https://maps.google.com/?q=2124+8th+Ave+S+Nashville+TN',
    eventType: 'social',
    isPublished: true,
    flyerId: 'flyer-001',
    createdAt: new Date('2026-05-01'),
    updatedAt: new Date('2026-05-01'),
  },
  {
    id: 'evt-002',
    title: 'Beginner Zouk Intensive',
    slug: 'beginner-zouk-intensive-june-2026',
    description:
      'A 3-hour intensive workshop for beginners covering the fundamentals of Brazilian Zouk. No partner or prior dance experience needed. Registration required.',
    startDatetime: new Date('2026-06-14T14:00:00-05:00'),
    endDatetime: new Date('2026-06-14T17:00:00-05:00'),
    locationName: 'Nashville Dance Studio',
    locationAddress: '1900 Belmont Blvd, Nashville, TN 37212',
    locationUrl: 'https://maps.google.com/?q=1900+Belmont+Blvd+Nashville+TN',
    eventType: 'workshop',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: 'evt-003',
    title: 'Zouk Fundamentals — Weekly Class',
    slug: 'zouk-fundamentals-class-june-19',
    description:
      'Ongoing weekly class series. This week: connection and lead/follow principles. Drop-ins welcome.',
    startDatetime: new Date('2026-06-19T19:00:00-05:00'),
    endDatetime: new Date('2026-06-19T20:30:00-05:00'),
    locationName: 'Centennial Arts Center',
    locationAddress: '330 31st Ave N, Nashville, TN 37203',
    locationUrl: 'https://maps.google.com/?q=330+31st+Ave+N+Nashville+TN',
    eventType: 'class',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-05-10'),
    updatedAt: new Date('2026-05-10'),
  },
  {
    id: 'evt-004',
    title: 'Nashville Zouk Social',
    slug: 'nashville-zouk-social-july-2026',
    description:
      'Our monthly social dance night. All levels welcome. Come dance Brazilian Zouk with Nashville\'s Zouk community.',
    startDatetime: new Date('2026-07-11T21:00:00-05:00'),
    endDatetime: new Date('2026-07-12T01:00:00-05:00'),
    locationName: 'The Standard',
    locationAddress: '2124 8th Ave S, Nashville, TN 37204',
    locationUrl: 'https://maps.google.com/?q=2124+8th+Ave+S+Nashville+TN',
    eventType: 'social',
    isPublished: true,
    flyerId: null,
    createdAt: new Date('2026-06-01'),
    updatedAt: new Date('2026-06-01'),
  },
]

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: 'inst-001',
    name: 'Sofia Carvalho',
    slug: 'sofia-carvalho',
    bio: 'Sofia has been dancing Brazilian Zouk for over 10 years and teaching for 6. Originally from São Paulo, she brings authentic Brazilian Zouk technique and musicality to Nashville.',
    photoUrl: 'https://placehold.co/400x400/f9a8d4/111827?text=SC',
    photoKey: null,
    instagramHandle: 'sofiazouk',
    displayOrder: 1,
    isActive: true,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'inst-002',
    name: 'Marcus Webb',
    slug: 'marcus-webb',
    bio: 'Marcus discovered Zouk in 2018 and has since trained with instructors across the US and Brazil. He focuses on lead technique, musicality, and making Zouk accessible to everyone.',
    photoUrl: 'https://placehold.co/400x400/a5b4fc/111827?text=MW',
    photoKey: null,
    instagramHandle: 'marcusdances',
    displayOrder: 2,
    isActive: true,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
]
